### ISSUE TITLE
Problem with ( ) in regex filter

### ISSUE THREAD

**Issue by lagomm** [cpainchaud/pan-configurator#69]
Hi, 

I have been trying to use the address-merger.php utils with a regex filter but I encountered an issue with the parseFromString function. 

I tried to launch the following command on Debian (PHP 5.6.30-0+deb8u1)
`php utils/address-merger.php in=api://172.20.192.101 location=vsys1 DupAlgorithm=SameAddress 'pickFilter=(name regex /^(?![HN]-)(.)*/)'`

```
***********************************************
*********** address-merger.php UTILITY **************

 - Downloading config from API... OK!
 - Detected platform type is 'panos'
 - Loading configuration through PAN-Configurator library... OK! (0.00 seconds, 0 memory)

* ** ERROR ** * invalid pickFilter was input: unsupported field name '?![hn]-' in expression '?![HN]-'

 *** Backtrace ***
0 ****
       derr()
       ::/home/valerie/pan-configurator/utils/address-merger.php line 207

```

But due to ( ) the parseFromString function seems to strip the filter too much and does not evaluate the regex filter entirely. I expected to use this filter /^(?![HN]-)(.)*/ to exclude every address beginning with H- or N-. 

Is this behaviour expected? Should I change the method to exclude such addresses or negate a filter?

Thanks in advance!

**Comment by cpainchaud** [comment]
Hi!

Problem comes from the () inside the filter itself : the parser is not able *yet* to understand it's parts of the REGEX rather than part of the filters formula.

You need to use this syntax instead:

'pickFilter=(name regex %subquery1)'  'subquery1=/^(?![HN]-)(.)*/'

Let me know how that goes ....

**Comment by lagomm** [comment]
Hello,

Thank you for this quick answer! I get the logic, I just tried the given syntax but I still have an issue with unknown string alias 'subquery1'

```
valerie@vpi-debian-dev:~/pan-configurator$ php utils/address-merger.php in=api://172.20.192.101 location=vsys1 DupAlgorithm=SameAddress 'pickFilter=(name regex %subquery1)' 'subquery1=/^(?![HN]-)(.)*/'    
***********************************************
*********** address-merger.php UTILITY **************

 - Downloading config from API... OK!
 - Detected platform type is 'panos'
 - Loading configuration through PAN-Configurator library... OK! (0.00 seconds, 0 memory)
 - pickFilter was input: (name regex %subquery1)
 - upper level search status : no
 - location 'vsys1' found
 - found 10 address Objects
 - DupAlgorithm selected: sameaddress
 - computing address values database ... OK!
 - found 4 duplicates values totalling 8 address objects which are duplicate


Now going after each duplicates for a replacement

 - value 'ip-netmask-172.20.200.4'

* ** ERROR ** * regular expression filter makes reference to unknown string alias 'subquery1'

 *** Backtrace ***
0 ****
       derr()
       ::/home/valerie/pan-configurator/lib/misc-classes/filters-Address.php line 266
1 ****
       {closure}()
       ::/home/valerie/pan-configurator/lib/misc-classes/class-RQuery.php line 642
2 ****
       RQueryContext::execute() @
           /home/valerie/pan-configurator/lib/misc-classes/class-RQuery.php line 120
3 ****
   RQuery::name regex %subquery1
       RQuery::matchSingleObject() @
           /home/valerie/pan-configurator/lib/misc-classes/class-RQuery.php line 253
4 ****
   RQuery::(name regex %subquery1)
       RQuery::matchSingleObject() @
           /home/valerie/pan-configurator/utils/address-merger.php line 374

```

**Comment by cpainchaud** [comment]
I just issued a code update, can you try that ? for some reasons , in address-merger subqueries were not parsed

**Comment by lagomm** [comment]
Hi, 
I pulled the update, but I am still running into the same issue : 

`
***********************************************
*********** address-merger.php UTILITY **************

 - Downloading config from API... OK!
 - Detected platform type is 'panos'
 - Loading configuration through PAN-Configurator library... OK! (0.00 seconds, 0 memory)
 - pickFilter was input: (name regex %subquery1)
 - upper level search status : no
 - location 'vsys1' found
 - found 10 address Objects
 - DupAlgorithm selected: sameaddress
 - computing address values database ... OK!
 - found 4 duplicates values totalling 8 address objects which are duplicate


Now going after each duplicates for a replacement

 - value 'ip-netmask-172.20.200.4'

* ** ERROR ** * regular expression filter makes reference to unknown string alias 'subquery1'

 *** Backtrace ***
0 ****
       derr()
       ::/home/valerie/pan-configurator/lib/misc-classes/filters-Address.php line 266
1 ****
       {closure}()
       ::/home/valerie/pan-configurator/lib/misc-classes/class-RQuery.php line 640
2 ****
       RQueryContext::execute() @
           /home/valerie/pan-configurator/lib/misc-classes/class-RQuery.php line 120
3 ****
   RQuery::name regex %subquery1
       RQuery::matchSingleObject() @
           /home/valerie/pan-configurator/lib/misc-classes/class-RQuery.php line 253
4 ****
   RQuery::(name regex %subquery1)
       RQuery::matchSingleObject() @
           /home/valerie/pan-configurator/utils/address-merger.php line 376

`

**Comment by cpainchaud** [comment]
I am sorry for that .... I fixed it everywhere but 1 place :/ Please get latest code again and try (I tested and it worked for me)

**Comment by lagomm** [comment]
Thank you very much for your help and this very efficient tool, now the regex is evaluated! I still have some issues with the result of the command but I think it is due to my regex, I will investigated. :)
